name: Publish AOE Titles
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Build and Push

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install all dependencies
        run: npm install
      
      - name: Build
        run: npm run build-only
      
      - name: Domain
        run: echo 'aoe.robdavis.dev' > dist/CNAME

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}" 